package com.procurement.contracting.exception

enum class ErrorType constructor(val code: String, val message: String) {
    CONTEXT("20.01", "Context parameter not found."),
    INVALID_TOKEN("20.02", "Invalid access token."),
    JSON_TYPE("00.00", "Invalid type: "),
    CANS_NOT_FOUND("00.01", "CANs not found."),
    CONTRACT_NOT_FOUND("00.02", "Contract not found."),
    INVALID_OWNER("00.03", "Invalid owner."),
    CAN_ID("00.04", "Invalid CAN id."),
    CONTRACT_ALREADY_CREATED("00.05", "Contract already created."),
    DOCUMENTS("00.06", "Documents are not valid"),
    NO_AMENDMENTS("00.07", "No amendments."),
    BUDGET_SUM("00.09", "Budget sum is invalid"),
    PLATFORM("00.10", "Invalid platform"),
    DATE("00.11", "Date Signed is empty"),
    NO_ACTIVE_AWARDS("00.12", "No active awards."),
    NO_COMPLETED_LOT("00.13", "No completed lot found."),
    NO_ITEMS("00.14", "No items for related lot found."),
    AWARDS_NOT_FOUND("00.15", "Awards not found."),
    CONTRACT_ID("00.16", "Invalid contract id."),
    AWARD_ID("00.17", "Invalid award id."),
    AWARD_VALUE("00.18", "Invalid award value."),
    ITEM_ID("00.19", "Invalid item id."),
    ITEM_AMOUNT("00.20", "Invalid item amount."),
    ITEM_CURRENCY("00.21", "Invalid item currency."),
    SUPPLIERS("00.22", "Invalid suppliers"),
    PERSONES("00.23", "Invalid persones identifier id."),
    TRANSACTIONS("00.24", "Invalid transactions"),
    BA_ITEM_ID("00.25", "Invalid budget allocation related item."),
    CONTRACT_STATUS_DETAILS("00.26", "Invalid contract status details."),
    CONTRACT_PERIOD("00.27", "Invalid contract period."),
    DOCS_RELATED_LOTS("00.28", "Invalid documents related lots."),
    MILESTONE_RELATED_ITEMS("00.29", "Invalid milestone related items."),
    MILESTONE_TYPE("00.30", "Invalid milestone type."),
    MILESTONE_DUE_DATE("00.31", "Invalid milestone due date."),
    CONFIRMATION_SOURCE("00.32", "Invalid confirmation request source."),
    CONFIRMATION_ITEM("00.33", "Invalid confirmation request related item."),
    PERSON_NOT_FOUND("00.34", "Person not found."),
    BF("00.35", "Invalid business functions of person."),
    TEMPLATE_NOT_FOUND("00.36", "Template not found."),
    CONTRACT_STATUS("00.37", "Invalid contract status."),
    BS_CURRENCY("00.38", "Invalid budget source currency."),
    MILESTONES_EMPTY("00.39", "Milestones must not be empty."),
    MILESTONE_ID("00.40", "Invalid milestone id."),
    INVALID_TR_RELATED_MILESTONES("00.41", "Invalid transaction related milestone id"),
    INVALID_DOCS_RELATED_LOTS("00.44", "Invalid document related lot id."),
    EMPTY_MILESTONE_RELATED_ITEM("00.45", "Milestone related item must not be empty."),
    BUYER_NAME_IS_EMPTY("00.46", "Buyer name must be not null."),
    BUYER_IS_EMPTY("00.47", "Buyer must be not null."),
    ORGANIZATION_AUTHORITY_PERSON_INVALID("20.05", "Person authority not found."),
    INVALID_REQUEST_ID("00.48", "invalid requestId."),
    INVALID_BUYER_ID("00.49", "invalid buyerId."),
    INVALID_RELATED_PERSON_ID("00.50", "invalid related person id."),
    INVALID_CONFIRMATION_REQUEST_DATE("00.51", "invalid Confirmation request date."),
    INVALID_SUPPLIER_ID("00.52", "invalid supplierId."),
    EMPTY_AWARD_RELATED_LOT("00.53", "Related lot in award in relatedProcess is empty."),
    AC_NOT_FOUND("00.54", "Awarded Contract not found"),
    CAN_NOT_FOUND("00.55", "CAN not found."),
    CAN_AC_ID_NOT_FOUND("00.56", "CAN acId not found"),
    INVALID_RESPONSE_ID("00.57", "invalid response id"),
    TREASURY_BUDGET_SOURCES("00.58", "Treasury budget sources is empty."),
    BUDGET_ALLOCATION("00.59", "Budget allocation is empty."),
    CONFIRMATION_REQUEST("00.59", "Confirmation request not found."),
    MILESTONE("00.59", "Milestone not found."),
    MILESTONE_RELATED_PARTY("00.60", "Invalid milestone related party."),
    INVALID_CAN_STATUS("00.61", "CAN has an invalid status to perform this operation."),
    CAN_FOR_LOT_EXIST("00.62", "Can for lot already exist."),
    DOCUMENTS_IS_NOT_EVALUATION_REPORTS("00.63", "DocumentsType must be evaluationReports"),
    SUPPLIERS_ID("00.64", "More than one value in set of supplier id."),
    AWARD_CURRENCY("00.65", "More than one value in set of currency."),
    CAN_ALREADY_USED("00.66", "CAN has been used for AC generation"),
    INVALID_AWARD_CURRENCY("00.67", "Invalid award currency."),
    INVALID_CAN_STATUS_DETAILS("00.68", "CAN has an invalid status details to perform this operation."),
    DUPLICATE_CAN_ID("00.69", "Duplicate CAN id."),
    INVALID_FORMAT_TOKEN("00.70", "Invalid format the Token."),
    INVALID_FORMAT_CAN_ID("00.71", "Invalid format the CAN id."),
    PERSONES_IN_SUPPLIERS_IS_EMPTY("00.72", "The list of the persones in the suppliers is empty."),
    BUSINESS_FUNCTIONS_IN_PERSONES_IN_SUPPLIER_IS_EMPTY("00.73", "The list of the business functions in the supplier is empty or missing."),
    DOCUMENTS_IN_BUSINESS_FUNCTION_IN_PERSON_IN_SUPPLIER_IS_EMPTY("00.74", "The list of the documents in the business function is empty or missing."),
    MAIN_ECONOMIC_ACTIVITIES_IN_DETAILS_IN_SUPPLIER_IS_EMPTY_OR_MISSING("00.75", "The list of the main economic activities in the details of the supplier is empty or missing."),
    BANK_ACCOUNTS_IN_DETAILS_IN_SUPPLIER_IS_EMPTY_OR_MISSING("00.76", "The list of the bank accounts in the details of the supplier is empty or missing."),
    ADDITIONAL_IDENTIFIERS_IN_SUPPLIER_IS_EMPTY_OR_MISSING("00.77", "The list of the additional identifiers in the supplier is empty or missing."),
    INVALID_BUSINESS_FUNCTIONS_TYPE("00.78", "A person with a business function type 'authority' should be used for the confirmation request."),
    INVALID_FORMAT_LOT_ID("00.79", "Invalid format the lot id."),
    INVALID_AMOUNT("00.80", "Invalid amount."),
    INVALID_CURRENCY("00.81", "Invalid currency."),
    NO_REGDATA("00.82", "RegData from treasury is absent."),
    INVALID_ATTRIBUTE("00.83", "Invalid attribute."),
    INVALID_FORMAT_OF_ATTRIBUTE("00.84", "Invalid attribute format.");
}
