package com.procurement.contracting.exception

enum class ErrorType constructor(val code: String, val message: String) {
    JSON_TYPE("00.00", "Invalid type: "),
    CANS_NOT_FOUND("00.01", "CANs not found."),
    CONTRACT_NOT_FOUND("00.02", "Contract not found."),
    OWNER("00.03", "Invalid owner."),
    CAN_ID("00.04", "Invalid CAN id."),
    CONTRACT_ALREADY_CREATED("00.05", "Contract already created."),
    DOCUMENTS("00.06", "Documents is not valid"),
    NO_AMENDMENTS("00.07", "No amendments."),
    BUDGET_SUM("00.09", "Budget sum is invalid"),
    PLATFORM("00.10", "Invalid platform"),
    DATE("00.11", "Date Signed is empty"),
    NO_ACTIVE_AWARDS("00.12", "No active awards."),
    NO_COMPLETED_LOT("00.13", "No completed lot found."),
    NO_ITEMS("00.14", "No items for related lot found."),
    AWARDS_NOT_FOUND("00.15", "Awards not found."),
    CONTRACT_ID("00.16", "Invalid contract id."),
    AWARD_ID("00.17", "Invalid award id."),
    AWARD_VALUE("00.18", "Invalid award value."),
    ITEM_ID("00.19", "Invalid item id."),
    ITEM_AMOUNT("00.20", "Invalid item amount."),
    ITEM_CURRENCY("00.21", "Invalid item currency."),
    SUPPLIERS("00.22", "Invalid suppliers"),
    PERSONES("00.23", "Invalid persones identifier id."),
    TRANSACTIONS("00.24", "Invalid transactions"),
    BA_ITEM_ID("00.25", "Invalid budget allocation related item."),
    CONTRACT_STATUS_DETAILS("00.26", "Invalid contract status details."),
    CONTRACT_PERIOD("00.27", "Invalid contract period."),
    DOCS_RELATED_LOTS("00.28", "Invalid documents related lots."),
    MILESTONE_RELATED_ITEMS("00.29", "Invalid milestone related items."),
    MILESTONE_TYPE("00.30", "Invalid milestone type."),
    MILESTONE_DUE_DATE("00.31", "Invalid milestone due date."),
    CONFIRMATION_SOURCE("00.32", "Invalid confirmation request source."),
    CONFIRMATION_ITEM("00.33", "Invalid confirmation request related item."),
    PERSON_NOT_FOUND("00.34", "Person not found."),
    BF("00.35", "Invalid business functions of person."),
    TEMPLATE_NOT_FOUND("00.36", "Template not found."),
    CONTRACT_STATUS("00.37", "Invalid contract status."),
    CONTEXT("20.01", "Context parameter not found."),
    INVALID_TOKEN("20.02", "Invalid access token.");
}
